#!/usr/bin/env perl

use Modern::Perl;
use FindBin;
use Pod::Usage;
use Time::Seconds;
use Task::Config;
use Task::Log;
use Try::Tiny;

use constant COMMANDS => [ qw/man help start stop pause resume switch break reset current list flush time summary status/ ];

=head1 NAME

  task - Simple task timer

=head1 SYNOPSIS

  task start bug fix           # start a timer
  task switch another bug fix  # stop the first and start a new one
  task stop                    # stop the second timer
  task start a third bug fix   # start a third
  task start part 1            # start a sub-timer without stopping the running timer
  task stop                    # stop the sub timer
  task stop                    # stop the third timer

=head1 COMMANDS

=head2 OVERVIEW

The general syntax is

  task [command] [args...]

where command is one of

  start [label]    - start a timer/sub-timer
  stop             - stop the current timer/sub-timer
  stop [label]     - stop sub-timers up to and including the labeled timer
  pause            - pause all timers
  resume           - resume paused timers
  switch [label]   - stop current timers and start labeled timer 
  break            - stop all timers
  reset [label]    - reset a timer
  current          - list the currently running timer or sub-timer
  list             - list all timers
  flush            - archive timers and start over
  time             - list the current time
  status           - list the current task as well as time
  summary          - list all tasks and times

Specific help for commands are available via

  task help [command]

The full man page is available via

  task man

=cut

{
    no strict 'refs';
    my $command = shift @ARGV;
    $command ~~ COMMANDS ? $command->(@ARGV) : pod2usage( -verbose => 1 );
}

# read the current log
sub tasks {
    my $new = sub { { label => shift, time => 0, subtasks => {} } };

    for (Task::Log::lines) {
        Task::List::add($_->{command}, $_->{label}, $_->{time});
    }

    return Task::List::all, Task::List::running;
}

# returns pretty format of time
sub pretty_time {
    my $time = new Time::Seconds shift @_;
    return $time->pretty;
}

=head2 man

Get the full man page.

  task man

=cut
sub man {
    pod2usage( -verbose => 2 );
}

=head2 help

Get help for one of the commands.

  task help [command]

=cut
sub help {
    my ($command) = @_;
    pod2usage( -verbose => 99, -sections => "COMMANDS/" . ($command ~~ COMMANDS ? $command : "OVERVIEW") );
}

=head2 start

Start the timer for a new or existing task.

  task start [task name]

=cut
sub start {
    my ($label) = @_ or die "No task specified to start";
    say "Starting $label";
    note "start", $label;
}

=head2 stop

Stop the timer for the current task or subtask.

  task stop

=cut
sub stop {
    my ($tasks, $running) = tasks();
    die "No tasks running to stop" unless @$running;
    note "stop";
    say "Stopped" . (@$running > 1 ? " subtask " : " ") . $running->[-1]{label};
}

=head2 reset

Reset the timer for a task (and removes all subtasks).

  task reset label

=cut
sub reset {
    my ($label) = @_ or die "No task specified to reset";
    my ($tasks, $running) = tasks();
    die "No task called $label" unless $tasks->{label};
    note "reset $label";
    say "Reset $label";
}

=head2 list

List all the tasks.

  task list

=cut
sub list {
    my ($tasks, $running) = tasks();

    my $level;
    $level = sub {
        my ($tasks, $prefix) = @_;
        for my $label (sort keys %$tasks) {
            say "$prefix$label\t" . pretty_time $tasks->{$label}{time};
            &$level($tasks->{$label}{subtasks}, "$prefix\\$label");
        }
    };

    &$level($tasks, "");
}

=head2 flush

Archive the log so we can start a new one.

=cut
sub flush {
    try { Task::Log::archive } catch { die "No log to flush\n" };
    say "Flushed log";
}

=head2 time

=cut
sub time {
    my ($label) = @_;
}

=head1 DESCRIPTION

This program times and logs tasks using a serries of log files stored in the log directory. 

=head1 CONFIGURATION

Configuration is taken from environment variables, ~/.task-timer, /etc/task-timer, in that order. The following variables can be used:

=head2 LOG_DIRECTORY

The directory to store logs in. The default is C<log/> relative to where the script is.

=head2 LOG_FILE

The file name to use for the log file. The default is C<current>.

=head2 SHORT

Can be set to change the output to be more suitable for use with scripts.

=head1 AUTHOR

Erik J. Sturcke

=cut
